[package]
name = "fever-ray"
version = "0.1.0"
authors = ["Rhys Powell <rhys@rpowell.me>"]
edition = "2018"

[dependencies]

image = "0.20.1"
clap = "2.20"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_yaml = "0.8.8"
rayon = "1.0.3"
